version: "2"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules    
    command: npm run start

  mydb:
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
    